esphome:
  name: "energy-dashboard"
  friendly_name: "Energie Dashboard"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome
    on_begin:
      - light.turn_off:
          id: display_backlight
          transition_length: 0s
      - lambda: "id(display_backlight).loop();"

# Backlight Control
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

light:
  - platform: monochromatic
    name: "Backlight"
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

# SPI für Display
spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

# I2C für Touchscreen
i2c:
  - id: touchscreen_bus
    sda: GPIO19
    scl:
      number: 45
      ignore_strapping_warning: true

# Display Konfiguration
display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    rotation: 270
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: false
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: false
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: false
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xCD, 0x00]
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

# Touchscreen
touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display
    i2c_id: touchscreen_bus

# Home Assistant Sensoren
sensor:
  - platform: homeassistant
    id: solar_power
    entity_id: sensor.solar_power
    internal: true
  
  - platform: homeassistant
    id: grid_power
    entity_id: sensor.grid_power
    internal: true
  
  - platform: homeassistant
    id: battery_power
    entity_id: sensor.battery_power
    internal: true
  
  - platform: homeassistant
    id: home_power
    entity_id: sensor.home_power
    internal: true
  
  - platform: homeassistant
    id: battery_soc
    entity_id: sensor.battery_soc
    internal: true

# Zeit von Home Assistant
time:
  - platform: homeassistant
    id: ha_time

# LVGL Konfiguration
lvgl:
  log_level: INFO
  color_depth: 16
  
  displays:
    - tft_display
  
  touchscreens:
    - tft_touch
  
  # Style Definitionen
  style_definitions:
    - id: style_circle
      bg_opa: TRANSP
      border_width: 0
      pad_all: 0
      radius: 1000
    
    - id: style_arc_green
      arc_width: 8
      arc_color: 0x00FF00
      arc_rounded: true
    
    - id: style_arc_red
      arc_width: 8
      arc_color: 0xFF0000
      arc_rounded: true
    
    - id: style_arc_blue
      arc_width: 8
      arc_color: 0x3399FF
      arc_rounded: true
    
    - id: style_arc_yellow
      arc_width: 8
      arc_color: 0xFFAA00
      arc_rounded: true
  
  # Widgets
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        # Zeit Display oben
        - label:
            id: time_label
            align: TOP_MID
            y: 15
            text: "12:14"
            text_font: roboto_32
            text_color: 0x4488FF
        
        # === SOLAR (Links Oben) ===
        - obj:
            id: solar_circle
            x: 50
            y: 90
            width: 100
            height: 100
            bg_color: 0x001100
            border_color: 0x00FF00
            border_width: 3
            radius: 50
            pad_all: 5
            widgets:
              - arc:
                  id: solar_arc
                  align: CENTER
                  width: 90
                  height: 90
                  start_angle: 270
                  end_angle: 270
                  rotation: 0
                  value: 0
                  min_value: 0
                  max_value: 100
                  arc_color: 0x003300
                  arc_width: 8
                  indicator:
                    arc_color: 0x00FF00
                    arc_width: 8
              
              - label:
                  id: solar_icon
                  align: CENTER
                  y: -15
                  text: "\U000F0A72"  # mdi:solar-power
                  text_font: icons_32
                  text_color: 0x00FF00
              
              - label:
                  id: solar_value
                  align: CENTER
                  y: 10
                  text: "0.0"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 30
                  text: "kW"
                  text_font: roboto_16
                  text_color: 0x888888
        
        # === GRID (Rechts Oben) ===
        - obj:
            id: grid_circle
            x: 330
            y: 90
            width: 100
            height: 100
            bg_color: 0x110000
            border_color: 0xFF0000
            border_width: 3
            radius: 50
            widgets:
              - arc:
                  id: grid_arc
                  align: CENTER
                  width: 90
                  height: 90
                  start_angle: 270
                  end_angle: 270
                  value: 0
                  min_value: 0
                  max_value: 100
                  arc_color: 0x330000
                  arc_width: 8
                  indicator:
                    arc_color: 0xFF0000
                    arc_width: 8
              
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F0239"  # mdi:transmission-tower
                  text_font: icons_32
                  text_color: 0xFF0000
              
              - label:
                  id: grid_value
                  align: CENTER
                  y: 10
                  text: "0.0"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 30
                  text: "kW"
                  text_font: roboto_16
                  text_color: 0x888888
        
        # === LEAF ICON Mitte ===
        - label:
            align: CENTER
            x: 0
            y: 0
            text: "\U000F0DEE"  # mdi:leaf
            text_font: icons_48
            text_color: 0x00AA44
        
        # === HOME (Rechts Mitte) ===
        - obj:
            id: home_circle
            x: 330
            y: 210
            width: 100
            height: 100
            bg_color: 0x001100
            border_color: 0x00FF00
            border_width: 3
            radius: 50
            widgets:
              - arc:
                  id: home_arc
                  align: CENTER
                  width: 90
                  height: 90
                  start_angle: 270
                  end_angle: 270
                  value: 0
                  min_value: 0
                  max_value: 100
                  arc_color: 0x003300
                  arc_width: 8
                  indicator:
                    arc_color: 0x00FF00
                    arc_width: 8
              
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F02DC"  # mdi:home
                  text_font: icons_32
                  text_color: 0x00FF00
              
              - label:
                  id: home_value
                  align: CENTER
                  y: 10
                  text: "0.0"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 30
                  text: "kW"
                  text_font: roboto_16
                  text_color: 0x888888
        
        # === BATTERY (Links Unten) ===
        - obj:
            id: battery_circle
            x: 50
            y: 330
            width: 100
            height: 100
            bg_color: 0x001122
            border_color: 0x3399FF
            border_width: 3
            radius: 50
            widgets:
              - arc:
                  id: battery_arc
                  align: CENTER
                  width: 90
                  height: 90
                  start_angle: 270
                  end_angle: 270
                  value: 0
                  min_value: 0
                  max_value: 100
                  arc_color: 0x002244
                  arc_width: 8
                  indicator:
                    arc_color: 0x3399FF
                    arc_width: 8
              
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F0079"  # mdi:battery
                  text_font: icons_32
                  text_color: 0x3399FF
              
              - label:
                  id: battery_value
                  align: CENTER
                  y: 10
                  text: "0.0"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 30
                  text: "kW"
                  text_font: roboto_16
                  text_color: 0x888888
        
        # === BACKUP HOME (Rechts Unten) ===
        - obj:
            id: backup_circle
            x: 330
            y: 330
            width: 100
            height: 100
            bg_color: 0x001100
            border_color: 0x00FF00
            border_width: 3
            radius: 50
            widgets:
              - arc:
                  id: backup_arc
                  align: CENTER
                  width: 90
                  height: 90
                  start_angle: 270
                  end_angle: 270
                  value: 0
                  min_value: 0
                  max_value: 100
                  arc_color: 0x003300
                  arc_width: 8
                  indicator:
                    arc_color: 0x00FF00
                    arc_width: 8
              
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F0ADB"  # mdi:home-lightning-bolt
                  text_font: icons_32
                  text_color: 0x00FF00
              
              - label:
                  id: backup_value
                  align: CENTER
                  y: 10
                  text: "0.0"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 30
                  text: "Backup"
                  text_font: roboto_16
                  text_color: 0x888888
        
        # System Info
        - label:
            id: system_info
            align: BOTTOM_LEFT
            x: 5
            y: -5
            text: "System OK"
            text_font: roboto_16
            text_color: 0x666666

# Fonts
font:
  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24
  
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
  
  - file: "gfonts://Roboto"
    id: roboto_32
    size: 32
  
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_32
    size: 32
    glyphs: [
      "\U000F0A72",  # solar-power
      "\U000F0239",  # transmission-tower
      "\U000F02DC",  # home
      "\U000F0079",  # battery
      "\U000F0DEE",  # leaf
      "\U000F0ADB",  # home-lightning-bolt
    ]
  
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_48
    size: 48
    glyphs: ["\U000F0DEE"]

# Updates
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: time_label
          text: !lambda |-
            auto time = id(ha_time).now();
            if (time.is_valid()) {
              static char buf[6];
              snprintf(buf, sizeof(buf), "%02d:%02d", time.hour, time.minute);
              return buf;
            }
            return "00:00";
      
      - lvgl.label.update:
          id: solar_value
          text: !lambda |-
            if (id(solar_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.1f", id(solar_power).state);
              return buf;
            }
            return "0.0";
      
      - lvgl.arc.update:
          id: solar_arc
          value: !lambda |-
            if (id(solar_power).has_state()) {
              int arc_val = (int)(id(solar_power).state / 5.0 * 100);
              return arc_val > 100 ? 100 : arc_val;
            }
            return 0;
      
      - lvgl.label.update:
          id: grid_value
          text: !lambda |-
            if (id(grid_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.1f", abs(id(grid_power).state));
              return buf;
            }
            return "0.0";
      
      - lvgl.arc.update:
          id: grid_arc
          value: !lambda |-
            if (id(grid_power).has_state()) {
              int arc_val = (int)(abs(id(grid_power).state) / 5.0 * 100);
              return arc_val > 100 ? 100 : arc_val;
            }
            return 0;
      
      - lvgl.label.update:
          id: home_value
          text: !lambda |-
            if (id(home_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.1f", id(home_power).state);
              return buf;
            }
            return "0.0";
      
      - lvgl.arc.update:
          id: home_arc
          value: !lambda |-
            if (id(home_power).has_state()) {
              int arc_val = (int)(id(home_power).state / 5.0 * 100);
              return arc_val > 100 ? 100 : arc_val;
            }
            return 0;
      
      - lvgl.label.update:
          id: battery_value
          text: !lambda |-
            if (id(battery_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.1f", abs(id(battery_power).state));
              return buf;
            }
            return "0.0";
      
      - lvgl.arc.update:
          id: battery_arc
          value: !lambda |-
            if (id(battery_soc).has_state()) {
              return (int)id(battery_soc).state;
            }
            return 0;