esphome:
  name: "energy-dashboard"
  friendly_name: "Energie Dashboard"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome
    on_begin:
      - light.turn_off:
          id: display_backlight
          transition_length: 0s
      - lambda: "id(display_backlight).loop();"

# Backlight Control
output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

light:
  - platform: monochromatic
    name: "Backlight"
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

# SPI f端r Display
spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

# I2C f端r Touchscreen
i2c:
  - id: touchscreen_bus
    sda: GPIO19
    scl:
      number: 45
      ignore_strapping_warning: true

# Display Konfiguration
display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    rotation: 270
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: false
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: false
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: false
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]
      - [0xCD, 0x00]
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

# Touchscreen
touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display
    i2c_id: touchscreen_bus

# Home Assistant Sensoren
sensor:
  - platform: homeassistant
    id: solar_power
    entity_id: sensor.solar_power
    internal: true
  
  - platform: homeassistant
    id: grid_power
    entity_id: sensor.grid_power
    internal: true
  
  - platform: homeassistant
    id: battery_power
    entity_id: sensor.battery_power
    internal: true
  
  - platform: homeassistant
    id: home_power
    entity_id: sensor.home_power
    internal: true
  
  - platform: homeassistant
    id: battery_soc
    entity_id: sensor.battery_soc
    internal: true
  
  - platform: homeassistant
    id: gas_power
    entity_id: sensor.gas_power
    internal: true
  
  - platform: homeassistant
    id: water_power
    entity_id: sensor.water_power
    internal: true

# Zeit von Home Assistant
time:
  - platform: homeassistant
    id: ha_time

# LVGL Konfiguration
lvgl:
  log_level: INFO
  color_depth: 16
  
  displays:
    - tft_display
  
  touchscreens:
    - tft_touch
  
  # Widgets
  pages:
    - id: main_page
      bg_color: 0x1a1a1a
      widgets:
        # === Energiefluss Linien (dunkel/transparent) ===
        
        # PV -> Home (vertikal mit Kurve nach rechts)
        - line:
            points:
              - 240, 130
              - 240, 180
              - 242, 190
              - 246, 200
              - 252, 208
              - 262, 216
              - 275, 222
              - 290, 228
              - 310, 232
              - 360, 238
            line_color: 0x332211
            line_width: 3
            line_rounded: true
        
        # Netz -> Home (horizontal)
        - line:
            points:
              - 130, 240
              - 180, 240
              - 220, 240
              - 260, 240
              - 310, 240
            line_color: 0x223344
            line_width: 3
            line_rounded: true
        
        # Batterie -> Home (vertikal mit Kurve nach rechts)
        - line:
            points:
              - 240, 350
              - 240, 300
              - 242, 290
              - 246, 280
              - 252, 272
              - 262, 264
              - 275, 258
              - 290, 252
              - 310, 248
              - 360, 242
            line_color: 0x332233
            line_width: 3
            line_rounded: true
        
        # Gas -> Home (vertikal nach unten)
        - line:
            points:
              - 360, 130
              - 360, 160
              - 360, 190
            line_color: 0x332211
            line_width: 3
            line_rounded: true
        
        # Wasser -> Home (vertikal nach oben)
        - line:
            points:
              - 360, 350
              - 360, 320
              - 360, 290
            line_color: 0x223344
            line_width: 3
            line_rounded: true
        
        # === Animierte Energiefluss Segmente ===
        - obj:
            id: flow_pv
            x: 238
            y: 130
            width: 4
            height: 15
            bg_color: 0xFFBB33
            radius: 2
            border_width: 0
        
        - obj:
            id: flow_grid
            x: 130
            y: 238
            width: 15
            height: 4
            bg_color: 0x00BBFF
            radius: 2
            border_width: 0
        
        - obj:
            id: flow_battery
            x: 238
            y: 330
            width: 4
            height: 15
            bg_color: 0xFF3399
            radius: 2
            border_width: 0
        
        - obj:
            id: flow_home
            x: 350
            y: 238
            width: 15
            height: 4
            bg_color: 0x00FF99
            radius: 2
            border_width: 0
        
        - obj:
            id: flow_gas
            x: 438
            y: 170
            width: 4
            height: 15
            bg_color: 0xFF6666
            radius: 2
            border_width: 0
        
        - obj:
            id: flow_water
            x: 438
            y: 290
            width: 4
            height: 15
            bg_color: 0x00DDFF
            radius: 2
            border_width: 0
        
        # === PV (Oben Mitte) ===
        - obj:
            id: pv_circle
            x: 190
            y: 30
            width: 100
            height: 100
            bg_color: 0x0a0a0a
            border_color: 0xFFBB33
            border_width: 3
            radius: 50
            scrollbar_mode: "off"
            clickable: false
            widgets:
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F0A72"
                  text_font: icons_32
                  text_color: 0xFFBB33
              
              - label:
                  id: pv_value
                  align: CENTER
                  y: 10
                  text: "0.12"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 28
                  text: "kWh"
                  text_font: roboto_12
                  text_color: 0x888888
        
        # === NETZ (Links) ===
        - obj:
            id: grid_circle
            x: 30
            y: 190
            width: 100
            height: 100
            bg_color: 0x0a0a0a
            border_color: 0x00BBFF
            border_width: 3
            radius: 50
            scrollbar_mode: "off"
            clickable: false
            widgets:
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F0239"
                  text_font: icons_32
                  text_color: 0x00BBFF
              
              - label:
                  id: grid_value
                  align: CENTER
                  y: 10
                  text: "0.00"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 28
                  text: "kWh"
                  text_font: roboto_12
                  text_color: 0x888888
        
        # === HOME (Rechts Mitte) ===
        - obj:
            id: home_circle
            x: 310
            y: 190
            width: 100
            height: 100
            bg_color: 0x0a0a0a
            border_color: 0x00FF99
            border_width: 3
            radius: 50
            scrollbar_mode: "off"
            clickable: false
            widgets:
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F02DC"
                  text_font: icons_32
                  text_color: 0x00FF99
              
              - label:
                  id: home_value
                  align: CENTER
                  y: 10
                  text: "7.62"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 28
                  text: "kWh"
                  text_font: roboto_12
                  text_color: 0x888888
        
        # === BATTERIE (Unten Mitte) ===
        - obj:
            id: battery_circle
            x: 190
            y: 350
            width: 100
            height: 100
            bg_color: 0x0a0a0a
            border_color: 0xFF3399
            border_width: 3
            radius: 50
            scrollbar_mode: "off"
            clickable: false
            widgets:
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F0079"
                  text_font: icons_32
                  text_color: 0xFF3399
              
              - label:
                  id: battery_value
                  align: CENTER
                  y: 10
                  text: "0.00"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 28
                  text: "kWh"
                  text_font: roboto_12
                  text_color: 0x888888
        
        # === GAS (Rechts Oben) ===
        - obj:
            id: gas_circle
            x: 310
            y: 30
            width: 100
            height: 100
            bg_color: 0x0a0a0a
            border_color: 0xFF6666
            border_width: 3
            radius: 50
            scrollbar_mode: "off"
            clickable: false
            widgets:
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F02E4"
                  text_font: icons_32
                  text_color: 0xFF6666
              
              - label:
                  id: gas_value
                  align: CENTER
                  y: 10
                  text: "1.42"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 28
                  text: "m続"
                  text_font: roboto_12
                  text_color: 0x888888
        
        # === WASSER (Rechts Unten) ===
        - obj:
            id: water_circle
            x: 310
            y: 350
            width: 100
            height: 100
            bg_color: 0x0a0a0a
            border_color: 0x00DDFF
            border_width: 3
            radius: 50
            scrollbar_mode: "off"
            clickable: false
            widgets:
              - label:
                  align: CENTER
                  y: -15
                  text: "\U000F058C"
                  text_font: icons_32
                  text_color: 0x00DDFF
              
              - label:
                  id: water_value
                  align: CENTER
                  y: 10
                  text: "0.11"
                  text_font: roboto_16
                  text_color: 0xFFFFFF
              
              - label:
                  align: CENTER
                  y: 28
                  text: "m続"
                  text_font: roboto_12
                  text_color: 0x888888

# Fonts
font:
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
  
  - file: "gfonts://Roboto"
    id: roboto_14
    size: 14
  
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
  
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_32
    size: 32
    glyphs: [
      "\U000F0A72",  # solar-power
      "\U000F0239",  # transmission-tower
      "\U000F02DC",  # home
      "\U000F0079",  # battery
      "\U000F02E4",  # fire (gas)
      "\U000F058C",  # water
    ]

# Updates
interval:
  - interval: 1s
    then:
      - lvgl.label.update:
          id: pv_value
          text: !lambda |-
            if (id(solar_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.2f", id(solar_power).state);
              return buf;
            }
            return "0.00";
      
      - lvgl.label.update:
          id: grid_value
          text: !lambda |-
            if (id(grid_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.2f", id(grid_power).state);
              return buf;
            }
            return "0.00";
      
      - lvgl.label.update:
          id: home_value
          text: !lambda |-
            if (id(home_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.2f", id(home_power).state);
              return buf;
            }
            return "0.00";
      
      - lvgl.label.update:
          id: battery_value
          text: !lambda |-
            if (id(battery_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.2f", id(battery_power).state);
              return buf;
            }
            return "0.00";
      
      - lvgl.label.update:
          id: gas_value
          text: !lambda |-
            if (id(gas_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.2f", id(gas_power).state);
              return buf;
            }
            return "0.00";
      
      - lvgl.label.update:
          id: water_value
          text: !lambda |-
            if (id(water_power).has_state()) {
              static char buf[8];
              snprintf(buf, sizeof(buf), "%.2f", id(water_power).state);
              return buf;
            }
            return "0.00";

  # Animation - animierte Segmente entlang der Kurven
  - interval: 30ms
    then:
      - lambda: |-
          static int pv_pos = 0;
          static int grid_pos = 0;
          static int battery_pos = 0;
          static int gas_pos = 0;
          static int water_pos = 0;
          
          // PV Flow (folgt der Kurve: vertikal -> Kurve -> horizontal zu Home)
          pv_pos = (pv_pos + 2) % 140;
          if (pv_pos < 50) {
            // Vertikal nach unten
            lv_obj_set_x(id(flow_pv), 238);
            lv_obj_set_y(id(flow_pv), 130 + pv_pos);
            lv_obj_set_width(id(flow_pv), 4);
            lv_obj_set_height(id(flow_pv), 15);
          } else if (pv_pos < 90) {
            // Kurve nach rechts
            int c = pv_pos - 50;
            lv_obj_set_x(id(flow_pv), 240 + c * 3);
            lv_obj_set_y(id(flow_pv), 180 + c * 1.45);
            lv_obj_set_width(id(flow_pv), 8);
            lv_obj_set_height(id(flow_pv), 8);
          } else {
            // Horizontal zu Home
            int c = pv_pos - 90;
            lv_obj_set_x(id(flow_pv), 310 + c);
            lv_obj_set_y(id(flow_pv), 236);
            lv_obj_set_width(id(flow_pv), 15);
            lv_obj_set_height(id(flow_pv), 4);
          }
          
          // Grid Flow (horizontal zu Home)
          grid_pos = (grid_pos + 2) % 180;
          lv_obj_set_x(id(flow_grid), 130 + grid_pos);
          lv_obj_set_y(id(flow_grid), 238);
          lv_obj_set_width(id(flow_grid), 15);
          lv_obj_set_height(id(flow_grid), 4);
          
          // Battery Flow (folgt der Kurve: vertikal -> Kurve -> horizontal zu Home)
          battery_pos = (battery_pos + 2) % 140;
          if (battery_pos < 50) {
            // Vertikal nach oben
            lv_obj_set_x(id(flow_battery), 238);
            lv_obj_set_y(id(flow_battery), 350 - battery_pos);
            lv_obj_set_width(id(flow_battery), 4);
            lv_obj_set_height(id(flow_battery), 15);
          } else if (battery_pos < 90) {
            // Kurve nach rechts
            int c = battery_pos - 50;
            lv_obj_set_x(id(flow_battery), 240 + c * 3);
            lv_obj_set_y(id(flow_battery), 300 - c * 1.2);
            lv_obj_set_width(id(flow_battery), 8);
            lv_obj_set_height(id(flow_battery), 8);
          } else {
            // Horizontal zu Home
            int c = battery_pos - 90;
            lv_obj_set_x(id(flow_battery), 310 + c);
            lv_obj_set_y(id(flow_battery), 244);
            lv_obj_set_width(id(flow_battery), 15);
            lv_obj_set_height(id(flow_battery), 4);
          }
          
          // Home Flow (horizontal innerhalb Home)
          lv_obj_set_x(id(flow_home), 360);
          lv_obj_set_y(id(flow_home), 238);
          
          // Gas Flow (vertikal nach unten zu Home)
          gas_pos = (gas_pos + 2) % 60;
          lv_obj_set_x(id(flow_gas), 358);
          lv_obj_set_y(id(flow_gas), 130 + gas_pos);
          lv_obj_set_width(id(flow_gas), 4);
          lv_obj_set_height(id(flow_gas), 15);
          
          // Water Flow (vertikal nach oben zu Home)
          water_pos = (water_pos + 2) % 60;
          lv_obj_set_x(id(flow_water), 358);
          lv_obj_set_y(id(flow_water), 350 - water_pos);
          lv_obj_set_width(id(flow_water), 4);
          lv_obj_set_height(id(flow_water), 15);