esphome:
  name: "guition-display"
  friendly_name: "Guition Display"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:

wifi:
  ssid: "TMesh"
  password: "yxcvbnm321"

  ap:
    ssid: "Guition Fallback"
    password: "12345678"

api:

ota:
  - platform: esphome
    on_begin:
      - light.turn_off:
          id: display_backlight
          transition_length: 0s
      - lambda: "id(display_backlight).loop();"

output:
  - platform: ledc
    id: backlight_output
    pin: GPIO38
    frequency: 150Hz
    min_power: 0.01
    zero_means_zero: true

light:
  - platform: monochromatic
    name: "Backlight"
    id: display_backlight
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 1s

spi:
  - id: lcd_spi
    clk_pin: GPIO48
    mosi_pin: GPIO47

i2c:
  - id: touchscreen_bus
    sda: GPIO19
    scl:
      number: 45
      ignore_strapping_warning: true

display:
  - platform: st7701s
    id: tft_display
    dimensions:
      width: 480
      height: 480
    rotation: 270
    spi_mode: MODE3
    data_rate: 2MHz
    color_order: RGB
    invert_colors: false
    cs_pin: 39
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
    pclk_frequency: 12MHz
    pclk_inverted: false
    hsync_pulse_width: 8
    hsync_front_porch: 10
    hsync_back_porch: 20
    vsync_pulse_width: 8
    vsync_front_porch: 10
    vsync_back_porch: 10
    update_interval: never
    auto_clear_enabled: false
    init_sequence:
      - 1
      - [0xFF, 0x77, 0x01, 0x00, 0x00, 0x10]  # CMD2_BKSEL_BK0
      - [0xCD, 0x00]  # disable MDT flag
    data_pins:
      red: [11, 12, 13, 14, 0]
      green: [8, 20, 3, 46, 9, 10]
      blue: [4, 5, 6, 7, 15]

touchscreen:
  - platform: gt911
    id: tft_touch
    display: tft_display
    i2c_id: touchscreen_bus

lvgl:
  displays:
    - tft_display
  touchscreens:
    - tft_touch
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
        # Home Consumption Circle (Center)
        - arc:
            id: home_arc
            x: 200
            y: 150
            width: 80
            height: 80
            start_angle: 0
            end_angle: 360
            bg_color: 0xFF0000  # Red for consumption
            value: 80
            max_value: 100
            indicator:
              arc_color: 0xFF0000
        - label:
            id: home_label
            text: "Haus\n800 W"
            x: 200
            y: 235
            text_color: 0xFFFFFF
            align: center

        # Solar Panel Circle (Top)
        - arc:
            id: solar_arc
            x: 200
            y: 10
            width: 80
            height: 80
            start_angle: 0
            end_angle: 360
            bg_color: 0xFFFF00  # Yellow for solar
            value: 75
            max_value: 100
            indicator:
              arc_color: 0xFFFF00
        - label:
            id: solar_label
            text: "Solar\n750 W"
            x: 200
            y: 95
            text_color: 0xFFFFFF
            align: center

        # Grid Circle (Right)
        - arc:
            id: grid_arc
            x: 350
            y: 150
            width: 80
            height: 80
            start_angle: 0
            end_angle: 360
            bg_color: 0x0000FF  # Blue for grid
            value: 50
            max_value: 100
            indicator:
              arc_color: 0x0000FF
        - label:
            id: grid_label
            text: "Netz\n500 W"
            x: 350
            y: 235
            text_color: 0xFFFFFF
            align: center

        # Battery Circle (Bottom)
        - arc:
            id: battery_arc
            x: 200
            y: 290
            width: 80
            height: 80
            start_angle: 0
            end_angle: 360
            bg_color: 0x00FF00  # Green for battery
            value: 60
            max_value: 100
            indicator:
              arc_color: 0x00FF00
        - label:
            id: battery_label
            text: "Batterie\n60%"
            x: 200
            y: 375
            text_color: 0xFFFFFF
            align: center

        # Vertical Arrows
        # Solar to Home
        - line:
            points:
              - "240,90"
              - "240,170"
            line_width: 4
            line_color: 0xFFFF00
        - line:
            points:
              - "240,170"
              - "230,160"
            line_width: 4
            line_color: 0xFFFF00
        - line:
            points:
              - "240,170"
              - "250,160"
            line_width: 4
            line_color: 0xFFFF00

        # Grid to Home
        - line:
            points:
              - "330,190"
              - "280,190"
            line_width: 4
            line_color: 0x0000FF
        - line:
            points:
              - "280,190"
              - "290,180"
            line_width: 4
            line_color: 0x0000FF
        - line:
            points:
              - "280,190"
              - "290,200"
            line_width: 4
            line_color: 0x0000FF

        # Battery to Home
        - line:
            points:
              - "240,310"
              - "240,230"
            line_width: 4
            line_color: 0x00FF00
        - line:
            points:
              - "240,230"
              - "230,240"
            line_width: 4
            line_color: 0x00FF00
        - line:
            points:
              - "240,230"
              - "250,240"
            line_width: 4
            line_color: 0x00FF00

# Dummy sensors for demonstration (replace with real sensors)
sensor:
  - platform: template
    name: "Solar Power"
    id: solar_power
    unit_of_measurement: "W"
    update_interval: 10s
    lambda: return 750;  # Example value
    on_value:
      then:
        - lvgl.label.update:
            id: solar_label
            text: !lambda return ("Solar\n" + std::to_string(int(x)) + " W").c_str();

  - platform: template
    name: "Grid Power"
    id: grid_power
    unit_of_measurement: "W"
    update_interval: 10s
    lambda: return 500;
    on_value:
      then:
        - lvgl.label.update:
            id: grid_label
            text: !lambda return ("Netz\n" + std::to_string(int(x)) + " W").c_str();

  - platform: template
    name: "Battery Level"
    id: battery_level
    unit_of_measurement: "%"
    update_interval: 10s
    lambda: return 60;
    on_value:
      then:
        - lvgl.label.update:
            id: battery_label
            text: !lambda return ("Batterie\n" + std::to_string(int(x)) + "%").c_str();

  - platform: template
    name: "Home Consumption"
    id: home_consumption
    unit_of_measurement: "W"
    update_interval: 10s
    lambda: return 800;
    on_value:
      then:
        - lvgl.label.update:
            id: home_label
            text: !lambda return ("Haus\n" + std::to_string(int(x)) + " W").c_str();
