# Energie Dashboard - Hauptkonfiguration
# Modulare Struktur für bessere Wartbarkeit

esphome:
  name: "energy-dashboard"
  friendly_name: "Energie Dashboard"

packages:
  hardware: !include base/hardware.yml
  network: !include base/network.yml
  ha_sensors: !include sensors/homeassistant.yml
  ui_fonts: !include ui/fonts.yml
  ui_loading: !include ui/loading.yml
  ui_layout: !include ui/layout.yml
  ui_animations: !include ui/animations.yml
  ui_power_table: !include ui/power_table_updates.yml
