# Home Assistant Sensoren und Zeit

# Globale Variablen
globals:
  - id: battery_capacity_kwh
    type: float
    restore_value: no
    initial_value: '13.0'  # Akkukapazität in kWh (anpassbar)
  
  - id: ha_connected
    type: bool
    restore_value: no
    initial_value: 'false'

# Home Assistant Sensoren
sensor:
  - platform: homeassistant
    id: solar_power
    entity_id: sensor.deye_wechselrichter_deye_tagliche_produktion
    internal: true
  
  - platform: homeassistant
    id: grid_power
    entity_id: sensor.deye_wechselrichter_deye_taglich_energie_bezogen
    internal: true
  
  - platform: homeassistant
    id: grid_feed_in
    entity_id: sensor.deye_wechselrichter_deye_taglich_energie_eingespiesen
    internal: true
  
  - platform: homeassistant
    id: home_power
    entity_id: sensor.strom_tagesverbrauch
    internal: true
  
  - platform: homeassistant
    id: battery_soc
    entity_id: sensor.deye_wechselrichter_deye_batterie_soc
    internal: true
  
  - platform: homeassistant
    id: gas_power
    entity_id: sensor.gas_tagesverbrauch
    internal: true
  
  - platform: homeassistant
    id: water_power
    entity_id: sensor.wasser_tagesverbrauch
    internal: true

# Zeit von Home Assistant
time:
  - platform: homeassistant
    id: ha_time
